---
- hosts: localhost
  become: no
  connection: local
  gather_facts: no

  #vars_prompt:
  #  - name: config_file
  #    prompt: "Which vars should I load?"
  #    private: no

  vars_files:
    - vars/all.yml
    - vars/home-pc.yml
    #- vars/{{ config_files }}.yml

  handlers:
    - include: handlers/handlers.yml

  tasks:
    #######################
    # Basic configuration #
    #######################
    # - include: tasks/conky.yml
      #    - include: tasks/disable-automute.yml
      #- include: tasks/enable-numlock.yml
      #- include: tasks/fonts-terminal.yml
      #   - include: tasks/fonts-desktop.yml
    - include: tasks/dnsutils.yml
    - include: tasks/nmap.yml
    - include: tasks/taskwarrior.yml
    - include: tasks/arandr.yml
    - include: tasks/neovim.yml
    - include: tasks/bat.yml
    - include: tasks/xclip.yml

      #- include: tasks/vim.yml user={{ user_item }}
      #with_items: '{{ users_inc_super }}'
      #loop_control:
      #  loop_var: user_item

    ########################
    #       SOFTWARE       #
    ########################

    # Internet
    # --------
    - include: tasks/firefox.yml


    # Sound & Video
    # -------------
    #- include: tasks/cmus.yml

    # Office
    # ------
    - include: tasks/freemind.yml

